export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const ADD_TO_WHISHLIST = 'ADD_TO_WHISHLIST';
export const REMOVE_FROM_WHISHLIST ='REMOVE_FROM_WHISHLIST';