let items = [
  {
    id: '1',
    name: 'Spoon',
    price: '60',
    quantity: 0,
    image: require('../assets/spoons.jpg'),
  },
  {
    id: '2',
    name: 'Glass',
    price: '350',
    quantity: 0,
    image: require('../assets/glass.jpg'),
  },
  {
    id: '3',
    name: 'Plate',
    price: '150',
    quantity: 0,
    image: require('../assets/plate.jpg'),
  },
  {
    id: '4',
    name: 'Chafing Dish',
    price: '2200',
    quantity: 0,
    image: require('../assets/chanfing1.jpeg'),
  },
  {
    id: '5',
    name: 'Jugg',
    price: '500',
    quantity: 0,
    image: require('../assets/jugset.jpg'),
  },
  {
    id: '6',
    name: 'Disposable Serving',
    price: '100',
    quantity: 0,
    image: require('../assets/DisposableServing.jpg'),
  },
  {
    id: '7',
    name: 'Cutlery',
    price: '450',
    quantity: 0,
    image: require('../assets/Cutlery.jpg'),
  },
  {
    id: '8',
    name: 'Cold pan',
    price: '850',
    quantity: 0,
    image: require('../assets/ColdPan.jpg'),
  },
  {
    id: '9',
    name: 'Disposable Plates',
    price: '20',
    quantity: 0,
    image: require('../assets/dis.jpg'),
  },
  {
    id: '10',
    name: 'Stainless Pan',
    price: '710',
    quantity: 0,
    image: require('../assets/StainlessPan.jpg'),
  },
  {
    id: '11',
    name: 'Salad Bar',
    price: '550',
    quantity: 0,
    image: require('../assets/Saladbar.jpg'),
  },
  {
    id: '12',
    name: 'Sticks',
    price: '620',
    quantity: 0,
    image: require('../assets/sticks.jpg'),
  },
  {
    id: '13',
    name: 'Pressure Cooker',
    price: '4500',
    quantity: 0,
    image: require('../assets/pressurecooker.jpg'),
  },

  {
    id: '15',
    name: 'Food Cleaner',
    price: '1500',
    quantity: 0,
    image: require('../assets/foodcleaner.jpg'),
  },
  {
    id: '16',
    name: 'Team Drum',
    price: '4500',
    quantity: 0,
    image: require('../assets/teadrum.jpeg'),
  },
  {
    id: '17',
    name: 'Food Warmer',
    price: '6500',
    quantity: 0,
    image: require('../assets/foodwarmer.jpg'),
  },

  {
    id: '18',
    name: 'Catle',
    price: '2000',
    quantity: 0,
    image: require('../assets/catle.jpeg'),
  },
  {
    id: '19',
    name: 'Donut Maker',
    price: '1200',
    quantity: 0,
    image: require('../assets/donutmaker.jpeg'),
  },
  {
    id: '20',
    name: 'Mixer',
    price: '1400',
    quantity: 0,
    image: require('../assets/mixer.jpeg'),
  },
  {
    id: '21',
    name: 'Spoons',
    price: '150',
    quantity: 0,
    image: require('../assets/spoon1.jpeg'),
  },
  {
    id: '22',
    name: 'Cream Scoop',
    price: '750',
    quantity: 0,
    image: require('../assets/creemscop.jpg'),
  },

  {
    id: '24',
    name: 'Choclate Fountain',
    price: '320',
    quantity: 0,
    image: require('../assets/choclatefountain.jpg'),
  },
  {
    id: '25',
    name: 'Chimney Cake',
    price: '720',
    quantity: 0,
    image: require('../assets/chimneycake.jpeg'),
  },
  {
    id: '26',
    name: 'Wire Shevling',
    price: '520',
    quantity: 0,
    image: require('../assets/wireshevling.jpeg'),
  },
  {
    id: '27',
    name: 'Chanfing Dish ',
    price: '8500',
    quantity: 0,
    image: require('../assets/chanfing1.jpeg'),
  },
  {
    id: '28',
    name: 'Carrying Dishes',
    price: '1500',
    quantity: 0,
    image: require('../assets/carryingdishes.jpg'),
  },
  {
    id: '29',
    name: 'Basket Gas',
    price: '12000',
    quantity: 0,
    image: require('../assets/basketgas.jpg'),
  },
  {
    id: '30',
    name: 'Stove',
    price: '9000',
    quantity: 0,
    image: require('../assets/stove.jpg'),
  },
  {
    id: '31',
    name: 'Pizza Pan',
    price: '780',
    quantity: 0,
    image: require('../assets/pans.jpeg'),
  },
  {
    id: '32',
    name: 'Mirror Chafing Dish',
    price: '5000',
    quantity: 0,
    image: require('../assets/mirrorchafing.jpg'),
  },
  {
    id: '33',
    name: 'Modern Chafing',
    price: '12000',
    quantity: 0,
    image: require('../assets/modernchafing.jpg'),
  },
  {
    id: '34',
    name: 'Bowl',
    price: '450',
    quantity: 0,
    image: require('../assets/bowl.jpeg'),
  },

  {
    id: '38',
    name: 'Creem Scoop',
    price: '350',
    quantity: 0,
    image: require('../assets/creemscop.jpg'),
  },
  {
    id: '39',
    name: 'Chairs',
    price: '2500',
    quantity: 0,
    image: require('../assets/chairs.jpeg'),
  },
  {
    id: '40',
    name: 'Stainless Pan',
    price: '750',
    quantity: 0,
    image: require('../assets/StainlessPan.jpg'),
  },
];

export default items;
